info:
  version: @pom.version@
  stage: ${info.stage}

logging:
  file: target/boot-admin-sample.log

spring:
  application:
    name: @pom.artifactId@
  boot:
    admin:
      url: http://localhost:8080
      client:
        name: ccctest
  cloud:
    config:
      enabled: false

endpoints:
  health:
    sensitive: false
